---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS - Cluster control plane'

Parameters:
  ClusterName:
    Type: String
    Default: "eks-cluster"
    Description: "Name for the EKS cluster."
  KubernetesVersion:
    Type: String
    Default: "1.20"
  RoleArn:
    Type: String
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "EKS - Cluster Configuration"
      Parameters:
      - ClusterName
      - KubernetesVersion
      - RoleArn
      - SecurityGroupIds
      - SubnetIds

Resources:
  EKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !Ref RoleArn
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIds

Outputs:
  Name:
    Value: !Ref EKS
  Arn:
    Value: !GetAtt EKS.Arn
  Endpoint:
    Value: !GetAtt EKS.Endpoint
  CAData:
    Value: !GetAtt EKS.CertificateAuthorityData
